title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://berthelemy.github.io/cookbook

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

include: ['_pages']